services:
  - type: web
    name: dusel-telegram-bot
    runtime: python
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: TURSO_URL
        sync: false
      - key: TURSO_TOKEN
        sync: false
