# Generated by Django 6.0.5 on 2026-05-31 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMenuRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavozim', models.CharField(max_length=50, unique=True)),
                ('faol', models.BooleanField(default=True)),
                ('izoh', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rol menyu',
                'verbose_name_plural': 'Rol menyular',
                'db_table': 'bot_menu_rol',
                'ordering': ['lavozim'],
            },
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-id'], 'verbose_name': 'Harakat', 'verbose_name_plural': 'Harakatlar'},
        ),
        migrations.AlterField(
            model_name='adminmsgmap',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='baholash',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faqkategoriya',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sorov',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='xabar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='xabarguruhi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BotTugma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(help_text='Tugma ustidagi yozuv', max_length=100)),
                ('buyruq', models.CharField(choices=[('sorov', "❓ So'rov / Muammo yozish"), ('yangi_klient', '🏪 Yangi Klient'), ('dokon_qoshish', "🏪 Do'kon qo'shish"), ('limit', "💰 Limit qo'shish"), ('faq', '📋 FAQ'), ('mening_klientlarim', '📋 Mening Klientlarim')], help_text='Tugma bosilganda ishga tushiriladigan buyruq', max_length=50)),
                ('qator', models.PositiveSmallIntegerField(default=1, help_text='Nechunchi qatorda (1 dan boshlab)')),
                ('ustun', models.PositiveSmallIntegerField(default=1, help_text="Qatordagi o'rni (1 dan boshlab)")),
                ('faol', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugmalar', to='bot_app.botmenurol')),
            ],
            options={
                'verbose_name': 'Tugma',
                'verbose_name_plural': 'Tugmalar',
                'db_table': 'bot_tugma',
                'ordering': ['qator', 'ustun'],
            },
        ),
    ]
