# Generated by Django 6.0.5 on 2026-05-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_add_bot_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSlashBuyruq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyruq', models.CharField(help_text='Masalan: faq (/ belgisisiz, kichik harf)', max_length=32, unique=True)),
                ('tavsif', models.CharField(help_text="Telegram da ko'rinadigan tavsif", max_length=256)),
                ('lavozim', models.CharField(blank=True, choices=[('', 'Barcha foydalanuvchilar'), ('Agent', 'Agent'), ('Supervisor', 'Supervisor'), ('Filial Rahbari', 'Filial Rahbari'), ('Operator', 'Operator'), ('Distribyutor', 'Distribyutor'), ('admin', 'Faqat Admin')], default='', help_text="Bo'sh = barcha; yoki aniq lavozim", max_length=50)),
                ('faol', models.BooleanField(default=True)),
                ('tartib', models.PositiveSmallIntegerField(default=0, help_text="Ro'yxatdagi tartib (kichikroq = yuqorida)")),
            ],
            options={
                'verbose_name': 'Slash buyruq',
                'verbose_name_plural': 'Slash buyruqlar',
                'db_table': 'bot_slash_buyruq',
                'ordering': ['tartib', 'buyruq'],
            },
        ),
        migrations.AddField(
            model_name='bottugma',
            name='extra',
            field=models.TextField(blank=True, help_text="matn_javob uchun: yuborish kerak bo'lgan matn", null=True),
        ),
        migrations.AlterField(
            model_name='bottugma',
            name='buyruq',
            field=models.CharField(choices=[('sorov', "❓ So'rov / Muammo yozish"), ('yangi_klient', '🏪 Yangi Klient'), ('dokon_qoshish', "🏪 Do'kon qo'shish"), ('limit', "💰 Limit qo'shish"), ('faq', '📋 FAQ'), ('mening_klientlarim', '📋 Mening Klientlarim'), ('matn_javob', '💬 Matn javobi (extra maydonga yozing)')], help_text='Tugma bosilganda ishga tushiriladigan buyruq', max_length=50),
        ),
    ]
