# Generated by Django 6.0.5 on 2026-05-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0003_add_slash_buyruq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='limit_summa',
            field=models.TextField(),
        ),
    ]
