# Generated by Django 6.0.5 on 2026-06-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0004_limit_summa_to_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler_name', models.CharField(max_length=100)),
                ('conv_key', models.CharField(max_length=100)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Suhbat holati',
                'verbose_name_plural': 'Suhbat holatlari',
                'db_table': 'bot_conversation_state',
                'unique_together': {('handler_name', 'conv_key')},
            },
        ),
    ]
